version: '3.3'

services:
  tarcotron2:
    build:
      context: ./tacotron2
      dockerfile: Dockerfile
#    runtime: nvidia
    volumes:
      - ./tacotron2:/tacotron2
      - /home/hwkang/dsba/code/kobart_voice_summarization/resamp_data:/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    command: sh run.sh

  waveglow:
    build:
      context: ./waveglow
      dockerfile: Dockerfile
#    runtime: nvidia
    volumes:
      - ./waveglow:/waveglow
      - ./tacotron2:/tacotron2
      - /home/hwkang/dsba/code/kobart_voice_summarization/resamp_data:/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
#    depends_on:
#      tarcotron2:
#          condition: service_completed_successfully
    command: python train.py -c config.json